import React, { useRef, useState } from 'react';
import { Download, Upload, ShieldCheck, FileCheck, CheckCircle2, AlertTriangle, RefreshCw } from 'lucide-react';
import { Item } from '../types';

interface BackupManagerProps {
  items: Item[];
  onImportBackup: (importedItems: Item[]) => void;
}

export default function BackupManager({ items, onImportBackup }: BackupManagerProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [importStatus, setImportStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState('');

  // Export state to beautiful download JSON backup
  const handleExport = () => {
    try {
      const dataStr = JSON.stringify(items, null, 2);
      const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
      
      const exportFileDefaultName = `WhereDidIPutIt_Backup_${new Date().toISOString().split('T')[0]}.json`;
      
      const linkElement = document.createElement('a');
      linkElement.setAttribute('href', dataUri);
      linkElement.setAttribute('download', exportFileDefaultName);
      linkElement.click();
    } catch (e) {
      console.error(e);
    }
  };

  // Import uploaded json backup and validate array schemas
  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const json = JSON.parse(event.target?.result as string);
        if (Array.isArray(json)) {
          // Primitive field schema validation
          const isValid = json.every(item => 
            item && 
            typeof item.id === 'string' && 
            typeof item.name === 'string' &&
            typeof item.room === 'string' &&
            typeof item.container === 'string'
          );

          if (isValid) {
            onImportBackup(json as Item[]);
            setImportStatus('success');
            setErrorMessage('');
            setTimeout(() => setImportStatus('idle'), 4000);
          } else {
            setImportStatus('error');
            setErrorMessage('Validation failed: Some objects inside the backup are missing required physical location properties.');
          }
        } else {
          setImportStatus('error');
          setErrorMessage('Backup file must contain a valid array of memorised objects.');
        }
      } catch (parseError) {
        setImportStatus('error');
        setErrorMessage('File decoding failed. Please upload a valid JSON format file generated by WhereDidIPutIt.');
      }
    };
    reader.readAsText(file);
    // Reset file input value
    if (e.target) {
      e.target.value = '';
    }
  };

  const triggerFileInput = () => {
    fileInputRef.current?.click();
  };

  return (
    <div className="bg-slate-900 border border-slate-800/80 rounded-2xl p-6 shadow-md">
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6">
        
        {/* Explain backup */}
        <div className="space-y-1 max-w-xl">
          <div className="flex items-center gap-2">
            <h3 className="font-display font-semibold text-base text-white">Import & Export Memory Backups</h3>
            <span className="bg-cyan-500/10 text-cyan-400 text-[10px] font-semibold border border-cyan-500/25 px-1.5 py-0.5 rounded uppercase tracking-wider font-mono">
              Local First
            </span>
          </div>
          <p className="text-xs text-slate-450 leading-relaxed">
            Since your physical item locations are completely private and never uploaded to public clouds, you can download an offline JSON backup file anytime to migrate to storage, device transfers, or keep secondary secure archives.
          </p>
        </div>

        {/* Action button grids */}
        <div className="flex flex-wrap items-center gap-3 w-full lg:w-auto">
          {/* Hidden File Input */}
          <input
            type="file"
            ref={fileInputRef}
            onClick={(e) => { (e.target as HTMLInputElement).value = ''; }}
            onChange={handleImport}
            accept=".json"
            className="hidden"
          />

          <button
            onClick={triggerFileInput}
            className="flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2.5 bg-slate-950 hover:bg-slate-850 text-slate-200 hover:text-white text-xs font-semibold rounded-xl border border-slate-800 hover:border-slate-700 transition cursor-pointer"
          >
            <Upload size={14} className="text-cyan-400" />
            Restore Backup (.json)
          </button>

          <button
            onClick={handleExport}
            disabled={items.length === 0}
            className="flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2.5 bg-gradient-to-r from-emerald-500/10 to-teal-500/10 hover:from-emerald-500/15 hover:to-teal-500/15 text-emerald-400 text-xs font-semibold rounded-xl border border-emerald-500/30 hover:border-emerald-500/40 transition disabled:opacity-50 disabled:pointer-events-none cursor-pointer"
          >
            <Download size={14} />
            Export Backup ({items.length} items)
          </button>
        </div>

      </div>

      {/* Response indicators */}
      {importStatus === 'success' && (
        <div className="mt-4 p-3 bg-emerald-500/10 border border-emerald-500/25 text-emerald-400 text-xs rounded-xl flex items-center gap-2 animate-fade-in">
          <CheckCircle2 size={16} />
          <span className="font-semibold">Backup imported successfully! Your physical storage catalog has been updated.</span>
        </div>
      )}

      {importStatus === 'error' && (
        <div className="mt-4 p-3 bg-rose-500/10 border border-rose-500/25 text-rose-400 text-xs rounded-xl flex items-center gap-2 animate-fade-in">
          <AlertTriangle size={16} />
          <span>{errorMessage}</span>
        </div>
      )}
    </div>
  );
}
